---
title: "Piramide poblacional"
author: "skb"
date: "2023-06-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Caracterizacion de la poblacion
piramide problacional

```{r piramide_poblacional}

# piramide poblacional por sexo y grupo_etario
datos_piramide <- data_per %>% 
  group_by(sexo, grupo_etario) %>% 
  summarise(n = n()) %>% 
  subset(sexo != "S.I.")
  
# invierto el signo de poblacion para los masculinos
datos_piramide$n <- ifelse(datos_piramide$sexo == "M", -datos_piramide$n, datos_piramide$n)

# grafico piramide
datos_piramide %>% 
  ggplot(aes(x = n, y = grupo_etario, fill = sexo)) +
  geom_col() +
  labs(title = "Piramide poblacional por <<sexo>> y <<grupo_etario>>")

# mejorar el resultado
n_range <- range(datos_piramide$n)

# valores de x sin negativos
intervalo <- round(max(abs(n_range[1]), abs(n_range[2])) / 10, 0)
n_range_seq <- seq(n_range[1], n_range[2], by = intervalo)

# pretty nos ayuda a armar valores de referencia redondeados
pop_range_breaks <- pretty(n_range, n = 7)

datos_piramide %>% 
  ggplot(aes(x = n, y = grupo_etario, fill = sexo)) +
  geom_col() +
  scale_x_continuous(breaks = pop_range_breaks,
                     labels = scales::comma(abs(pop_range_breaks))) + ## ver que le vuelvo a meter ABS. 
  labs(title = "Piramide poblacional por <<sexo>> y <<grupo_etario>>") +
  xlab(label = "Población") +
  ylab(label = "Grupo etario") +
  theme(legend.position = "right") + ## ubicar la leyenda
  theme_classic() ## 
ggsave(paste0("png/piramide_poblacional_","sexo_grupo_etario", ".png"))

# ?text ## para agregar valores, no me funciono

```

Gracias Elio por el material: 
Me hubiera gustado y queda pendiente terminar la biblio generando una funcion como explica en el paso a paso.
https://www.njtierney.com/post/2022/08/09/ggplot-pyramid/
